[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
builders_anchor_vault = "BU2EcRFU3RKpSCAFVGcBjmBUcQnrRjsHKnr97dMu9oYJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
